Change fetch all queries
adahandle/adahandle-static pull request #147
Opened 2021-11-16 01:22 UTC by guavajellyaaron

2021-11-16 03:40 UTC, cjkoepke approved these changes
@guavajellyaaron minor comments, MWR!

2021-11-16 03:40 UTC, cjkoepke commented on netlify/helpers/firebase.ts
> +    .get()
@guavajellyaaron Do we want to force a single result here? i.e. `.limit(1)`

2021-11-16 03:40 UTC, cjkoepke commented on netlify/helpers/firebase.ts
> +    .where("handle", "==", handle).limit(1)
@guavajellyaaron same here, `.limit(1)`

2021-11-18 16:34 UTC, cjkoepke requested changes

2021-11-18 16:34 UTC, cjkoepke commented on netlify/helpers/firebase.ts
> +      return snapshot?.docs[0]?.data() as ActiveSessionType;
@guavajellyaaron We're only returning the first result here. Shouldn't it be all of them?

2021-11-22 16:38 UTC, guavajellyaaron commented on netlify/helpers/firebase.ts
> +      return snapshot?.docs[0]?.data() as ActiveSessionType;
@cjkoepke This function was updated to find a matching sessions for a particular handle or phone number. We're only checking if it exists.

2021-11-22 17:59 UTC, cjkoepke commented on netlify/helpers/firebase.ts
> +      return snapshot?.docs[0]?.data() as ActiveSessionType;
@guavajellyaaron Ah, I see. Let's change the function name then to be singular.

2021-11-22 17:59 UTC, cjkoepke approved these changes
change function name but MWR

2021-11-23 01:14 UTC, guavajellyaaron commented on netlify/helpers/firebase.ts
> +      return snapshot?.docs[0]?.data() as ActiveSessionType;
@cjkoepke Good call!

2021-11-23 16:24 UTC, cjkoepke approved these changes
LGTM

2021-11-23 16:24 UTC, merged